### ISSUE TITLE
Question in Paper About IBP

### ISSUE THREAD

**Issue by magicrane** [hito2448/CRD#1]
Thanks to your awesome work！
However , I am confused when i read your paper at Sec 4:
![image](https://github.com/user-attachments/assets/fac8e822-157c-450b-a61c-247e912eb039)
If we only consider the branch of A, reverse distillation is intended to have the student decoder generate a normal representation. By BP operations, the normal information of modality B is integrated into A, and together they serve as the input to OCBE, then input into the decoder should yield a normal representation. Then, if the IBP operation amplifies the anomaly values of modality B and fuses them with the output of the decoder, won't the final result become abnormal?
 If you can answer this question for me, I would be extremely grateful. Looking forward to your reply！！

**Comment by hito2448** [comment]
We suspect your confusion may arise from a mistake in Figure 5 of the paper. The use of the same color to represent anomalies in different modalities is misleading. We apologize for this and have redesigned the schematic diagram to better reflect the feature transformation process during inference. Hopefully, the new diagram will address your concerns more clearly:

![image](https://github.com/hito2448/CRD/blob/main/docs/inference.jpg)

In Reverse Distillation, the assumption is that the OCBE allows the student decoder to generate normal representations. We agree with this assumption and extend the reverse distillation architecture to multimodal anomaly detection scenario in the **Multi-branch Distillation** section.

However, we identified a key issue when we only design separate branches for each modality: **anomaly smoothing issue** (as mentioned on pages 4 and 5 of the paper). In unsupervised multimodal anomaly detection, anomaly maps from different modalities are often combined using addition or multiplication. Thus, if the anomaly map of modality A dominates the combined map, anomalies in modality B may be overlooked.

Based on this, the goal of our proposed **Crossmodal Amplifier** is to allow modality A’s branch to sense anomalies from modality B, and for these anomalies to manifest in the anomaly map generated by modality A’s branch (from the perspective of modality A).

In practice, we design **IBP** module. During training, IBP aligns features between modalities. Specifically, for the modality A’s branch, we align modality B’s encoder features with those of modality A. Since only normal samples are used in training, IBP learns how to align modality B’s features to modality A in normal regions. Therefore, when there are anomalous regions in modality B, the output features of IBP are generated in these regions by exceptions with large feature distances from the encoder features of modality A (no matter if modality A is anomalous). And the amplification and reduction process of the number of channels in IBP amplifies the impact of abnormal features on alignment. This allows modality A's branch to perceive modality B’s anomalies.

Feel free to reach out if you have further questions or suggestions!

**Comment by magicrane** [comment]
I would like to express my gratitude for your lucid presentation and the highly comprehensible framework diagram. The new diagram has elegantly resolved my queries, allowing me to better appreciate your exemplary work. That is to say, after the fusion of the last two modalities, your objective here is to incorporate the anomalies of Modality B while processing Modality A, in order to obtain a more rational anomaly map. Conversely, when processing Modality B, Modality A is also taken into account. However, I have a minor query regarding your approach: as you mentioned, the anomaly mapping of different modalities is typically achieved through addition. When processing Modalities A and B to obtain two anomaly maps, would it be feasible to normalize them and then sum them to maintain consistency in the scale of features? Could this also, to some extent, address the anomaly smoothing issue you referred to?

**Comment by hito2448** [comment]
To answer your query, we'd like to present a toy example: 

**Modality A's Anomaly Map:**

$$ M^A = \begin{bmatrix} 
0.13 & 0.31 & 0.64 & 0.27 \\ 
0.24 & 0.72 & 0.41 & 0.34 \\ 
0.22 & 0.13 & 0.15 & 0.17 \\ 
0.11 & 0.35 & 0.09 & 0.21 \\ 
\end{bmatrix}$$

**Modality B's Anomaly Map:**

$$ M^B = \begin{bmatrix}
0.14 & 0.12 & 0.05 & 0.26 \\
0.21 & 0.95 & 0.24 & 0.09 \\
0.28 & 0.14 & 0.21 & 0.29 \\
0.31 & 0.18 & 0.63 & 0.22 \\
\end{bmatrix}$$

Normalize both anomaly maps using Z-Score Normalization and fuse them (Here we assume the mean and standard deviation for Modality A are 0.25 and 0.12, respectively, while for Modality B, they are 0.13 and 0.09, respectively.):

**Normalized Modality A's Anomaly Map:**

$$
M^A_{norm} = \begin{bmatrix}
-1.0000 & 0.5000 & 3.2500 & 0.1670 \\
-0.0833 & 3.9167 & 1.3333 & 0.7500 \\
-0.2500 & -1.000 & -0.8333 & -0.6667 \\
-1.1667 & 0.8333 & -1.3333 & -0.3333 \\
\end{bmatrix}
$$

**Normalized Modality B's Anomaly Map:**

$$
M^B_{norm} = \begin{bmatrix}
0.1111 & -0.1111 & -0.8889 & 1.4444 \\
0.8889 & 9.1111 & 1.2222 & -0.4444 \\
1.6667 & 0.1111 & 0.8889 & 1.7778 \\
2.0000 & 0.5556 & 5.5556 & 1.0000 \\
\end{bmatrix}
$$

**Summed Anomaly Map:**

$$
M = M^A_{norm} + M^B_{norm} = \begin{bmatrix}
-0.8889 & 0.3889 & 2.3611 & 1.6114 \\
0.8056 & 13.0278 & 2.5556 & 0.3056 \\
1.4167 & -0.8889 & 0.0556 & 1.1111 \\
0.8333 & 1.3889 & 4.2222 & 0.6667 \\
\end{bmatrix}
$$

In the original individual anomaly maps, these values were relatively higher, indicating significant anomalies. However, after fusion, the anomaly values at positions [0,2] in Modality A and [3,2] in Modality B are similar with the values of normal pixels. This example demonstrates that normalization, in some extreme cases, still cannot resolve the anomaly smoothing issue. Therefore, we believe that incorporating multimodal interactions during training is necessary to address this issue effectively.

**Comment by magicrane** [comment]
Thank you for your patience! It makes me more aware of the significance of your work. Finally, I would like to express my sincere thanks to you again : )

**Comment by clelouch** [comment]
> We suspect your confusion may arise from a mistake in Figure 5 of the paper. The use of the same color to represent anomalies in different modalities is misleading. We apologize for this and have redesigned the schematic diagram to better reflect the feature transformation process during inference. Hopefully, the new diagram will address your concerns more clearly:
> 
> ![image](https://github.com/hito2448/CRD/blob/main/docs/inference.jpg)
> 
> In Reverse Distillation, the assumption is that the OCBE allows the student decoder to generate normal representations. We agree with this assumption and extend the reverse distillation architecture to multimodal anomaly detection scenario in the **Multi-branch Distillation** section.
> 
> However, we identified a key issue when we only design separate branches for each modality: **anomaly smoothing issue** (as mentioned on pages 4 and 5 of the paper). In unsupervised multimodal anomaly detection, anomaly maps from different modalities are often combined using addition or multiplication. Thus, if the anomaly map of modality A dominates the combined map, anomalies in modality B may be overlooked.
> 
> Based on this, the goal of our proposed **Crossmodal Amplifier** is to allow modality A’s branch to sense anomalies from modality B, and for these anomalies to manifest in the anomaly map generated by modality A’s branch (from the perspective of modality A).
> 
> In practice, we design **IBP** module. During training, IBP aligns features between modalities. Specifically, for the modality A’s branch, we align modality B’s encoder features with those of modality A. Since only normal samples are used in training, IBP learns how to align modality B’s features to modality A in normal regions. Therefore, when there are anomalous regions in modality B, the output features of IBP are generated in these regions by exceptions with large feature distances from the encoder features of modality A (no matter if modality A is anomalous). And the amplification and reduction process of the number of channels in IBP amplifies the impact of abnormal features on alignment. This allows modality A's branch to perceive modality B’s anomalies.
> 
> Feel free to reach out if you have further questions or suggestions!

The image is not available. Could you please reupload it?
